posthelper: add actions and parse args for them
actions:
 - name
 - edit

notes:
 - prompt for getting slug prints to stderr to not interfere with name
   action

diff --git a/post b/post
--- a/post
+++ b/post
@@ -4,8 +4,36 @@ set -e
 
 [ -n "${DEBUG}" ] && set -x
 
-_date=$(date '+%F' --date="${1:-now}")
+ACTION_edit=0
+ACTION_name=1 #default action
 
+convert_date_string(){ if { date '+%F' --date="${1}" 2>/dev/null;};then return 0;else >&2 echo 'invalid date string provided'; return 1;fi; }
+
+while [ ${#} -gt 0 ]; do
+	case "${1}" in
+		--edit|-e)
+			ACTION_edit=1
+			ACTION_name=0
+			;;
+		--name|-n)
+			ACTION_name=1
+			ACTION_edit=0
+			;;
+		--date|-d)
+			_date=$(convert_date_string "${2}")
+			shift 1
+			;;
+		--date=*)
+			_date=$(convert_date_string "${1##*=}")
+			;;
+		*)
+			_date=$(convert_date_string "${1}")
+		;;
+	esac
+	shift 1
+done
+
+_date="${_date:-$(convert_date_string now)}"
 _postpattern="_posts/${_date}-*.md"
 
 if [ -z "${post}" ]; then
@@ -13,10 +41,11 @@ if [ -z "${post}" ]; then
 fi
 
 if [ -z "${post}" ]; then
-    echo creating post for ${_date}
-    read -p "NAME/SLUG REQUIRED: " slug
+    >&2 echo creating post for ${_date}
+    >&2 read -p "NAME/SLUG REQUIRED: " slug
     post="${_postpattern%%\**}${slug}${_postpattern##*\*}"
     cp -u _drafts/_post-template.md "${post}"
 fi
 
-"${EDITOR:-vi}" "${post}"
+if [ "${ACTION_edit}" -eq 1 ]; then "${EDITOR:-vi}" "${post}"; fi
+if [ "${ACTION_name}" -eq 1 ]; then printf '%s\n' "${post}"; fi
